const { sequelize } = require('./models')
const express = require('express')
const cors = require('cors')
const app = express()
app.use(cors())
app.use(express.json())

const registerRoute = require('./routes/auth/register')
const loginRoute = require('./routes/auth/login')
const valuesRoute = require('./routes/helpers/values')
const rmRoute = require('./routes/raw-material')
const shearingRoute = require('./routes/shearing')
const meltingRoute = require('./routes/melting')
const scrapRoute = require('./routes/scrap')
const productionRoute = require('./routes/production')
const deliveryRoute = require('./routes/delivery')

app.use('/register', registerRoute)
app.use('/login', loginRoute)
app.use("/values", valuesRoute)
app.use("/raw-material-entries", rmRoute)
app.use("/shearing-entries", shearingRoute)
app.use("/melting-entries", meltingRoute)
app.use("/scrap", scrapRoute)
app.use("/production-entries", productionRoute)
app.use("/delivery-entries", deliveryRoute)

app.listen(3000)